### PR TITLE
FIX #61 - connection state was resolved too early

### LINKED ISSUE #61: Websocket reconnect issue with multiple clients: getting ghost clients
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included `nats-server -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:

nats-server version 2.2.0-beta.34
synadia/nats-server:nightly-20201204

#### OS/Container environment:

Linux / Docker container

#### Steps or code to reproduce the issue:

Create two basic nats.ws client with the following connection options:
```
{ 
      name: 'client-',
      servers: 'ws://localhost:9222',
      token: '3secret',
      timeout: 2000,
      noEcho: true,
      maxReconnectAttempts: 10,
      pingInterval: 3000,
      maxPingOut: 2,
}
```

Create a nats server with the following Docker image: synadia/nats-server:nightly-20201204 and the following config:
```
listen: 127.0.0.1:4222
debug:   false
trace:   true

authorization: {
    token: "3secret"
}

websocket: {
    listen: 0.0.0.0:9222
    no_tls: true
}
```

1.  Start the server
2. Connect client 1
3. Connect client 2
4. Wait 5s
5. Kill the server
6. Wait 5s
7. Start the server

This will help reproduction: [issue-1778.zip](https://github.com/nats-io/nats-server/files/5710706/issue-1778.zip)

#### Expected result:

The server starts, both client try to reconnect. The server shows two "client connection created"  and two "CONNECT" messages which authenticates fine. The clients get a "reconnect" status message.

```
[1] 2020/12/17 16:03:02.342424 [INF] Starting nats-server version 2.2.0-beta.34
[1] 2020/12/17 16:03:02.342526 [DBG] Go build version go1.14.12
[1] 2020/12/17 16:03:02.342532 [INF] Git commit [8e095759]
[1] 2020/12/17 16:03:02.342563 [INF] Using configuration file: /nats/server.conf
[1] 2020/12/17 16:03:02.342615 [DBG] Created system account: "$SYS"
[1] 2020/12/17 16:03:02.343162 [INF] Listening for websocket clients on ws://0.0.0.0:9222
[1] 2020/12/17 16:03:02.343199 [WRN] Websocket not configured with TLS. DO NOT USE IN PRODUCTION!
[1] 2020/12/17 16:03:02.343208 [DBG] Get non local IPs for "0.0.0.0"
[1] 2020/12/17 16:03:02.343425 [DBG]   ip=172.17.0.2
[1] 2020/12/17 16:03:02.343543 [INF] Listening for client connections on 127.0.0.1:4222
[1] 2020/12/17 16:03:02.343579 [INF] Server id is NAZRKRPGYC56ZINY76B4R6OTGSKMI2VZB5KO4AVCYDD7AGSNH54QJAIF
[1] 2020/12/17 16:03:02.343584 [INF] Server name is NAZRKRPGYC56ZINY76B4R6OTGSKMI2VZB5KO4AVCYDD7AGSNH54QJAIF
[1] 2020/12/17 16:03:02.343588 [INF] Server is ready
[1] 2020/12/17 16:03:02.637848 [DBG] 172.17.0.1:45256 - wid:2 - Client connection created
[1] 2020/12/17 16:03:02.642905 [TRC] 172.17.0.1:45256 - wid:2 - <<- [CONNECT {"protocol":1,"version":"1.0.0-114","lang":"nats.ws","echo":false,"verbose":false,"pedantic":false,"name":"client-","auth_token":"3secret"}]
[1] 2020/12/17 16:03:02.643120 [TRC] 172.17.0.1:45256 - wid:2 - "v1.0.0-114:nats.ws:client-" - <<- [PING]
[1] 2020/12/17 16:03:02.643167 [TRC] 172.17.0.1:45256 - wid:2 - "v1.0.0-114:nats.ws:client-" - ->> [PONG]
[1] 2020/12/17 16:03:02.648342 [DBG] 172.17.0.1:45260 - wid:3 - Client connection created
[1] 2020/12/17 16:03:02.654492 [TRC] 172.17.0.1:45260 - wid:3 - <<- [CONNECT {"protocol":1,"version":"1.0.0-114","lang":"nats.ws","echo":false,"verbose":false,"pedantic":false,"name":"client-","auth_token":"3secret"}]
[1] 2020/12/17 16:03:02.654558 [TRC] 172.17.0.1:45260 - wid:3 - "v1.0.0-114:nats.ws:client-" - <<- [PING]
[1] 2020/12/17 16:03:02.654564 [TRC] 172.17.0.1:45260 - wid:3 - "v1.0.0-114:nats.ws:client-" - ->> [PONG]
[1] 2020/12/17 16:03:04.752051 [DBG] 172.17.0.1:45256 - wid:2 - "v1.0.0-114:nats.ws:client-" - Client Ping Timer
[1] 2020/12/17 16:03:04.752120 [TRC] 172.17.0.1:45256 - wid:2 - "v1.0.0-114:nats.ws:client-" - ->> [PING]
[1] 2020/12/17 16:03:04.756260 [TRC] 172.17.0.1:45256 - wid:2 - "v1.0.0-114:nats.ws:client-" - <<- [PONG]
[1] 2020/12/17 16:03:04.896866 [DBG] 172.17.0.1:45260 - wid:3 - "v1.0.0-114:nats.ws:client-" - Client Ping Timer
[1] 2020/12/17 16:03:04.896939 [TRC] 172.17.0.1:45260 - wid:3 - "v1.0.0-114:nats.ws:client-" - ->> [PING]
[1] 2020/12/17 16:03:04.902107 [TRC] 172.17.0.1:45260 - wid:3 - "v1.0.0-114:nats.ws:client-" - <<- [PONG]
[1] 2020/12/17 16:03:05.666494 [TRC] 172.17.0.1:45256 - wid:2 - "v1.0.0-114:nats.ws:client-" - <<- [PING]
[1] 2020/12/17 16:03:05.666565 [TRC] 172.17.0.1:45256 - wid:2 - "v1.0.0-114:nats.ws:client-" - ->> [PONG]
[1] 2020/12/17 16:03:06.516147 [TRC] 172.17.0.1:45260 - wid:3 - "v1.0.0-114:nats.ws:client-" - <<- [PING]
[1] 2020/12/17 16:03:06.516183 [TRC] 172.17.0.1:45260 - wid:3 - "v1.0.0-114:nats.ws:client-" - ->> [PONG]
```

#### Actual result:

Sometime, the expected result occurs, sometimes, we can see 4 "Client connection created" messages with 4 different wid. Only two CONNECT messages are received. The two connections that don't have a CONNECT message get an Authentication Timeout message (result of auth enabled). The clients get a "NATS connection closed 'Authentication Timeout'" failure.

```
[1] 2020/12/17 16:03:13.638188 [INF] Starting nats-server version 2.2.0-beta.34
[1] 2020/12/17 16:03:13.638290 [DBG] Go build version go1.14.12
[1] 2020/12/17 16:03:13.638296 [INF] Git commit [8e095759]
[1] 2020/12/17 16:03:13.638301 [INF] Using configuration file: /nats/server.conf
[1] 2020/12/17 16:03:13.638331 [DBG] Created system account: "$SYS"
[1] 2020/12/17 16:03:13.638993 [INF] Listening for websocket clients on ws://0.0.0.0:9222
[1] 2020/12/17 16:03:13.639030 [WRN] Websocket not configured with TLS. DO NOT USE IN PRODUCTION!
[1] 2020/12/17 16:03:13.639039 [DBG] Get non local IPs for "0.0.0.0"
[1] 2020/12/17 16:03:13.639426 [DBG]   ip=172.17.0.2
[1] 2020/12/17 16:03:13.639545 [INF] Listening for client connections on 127.0.0.1:4222
[1] 2020/12/17 16:03:13.639577 [INF] Server id is NAOYR6QS2GMEQG4TFZF7D3SNFWEL536KSW57ZJUTSPEMZ5UGFF6UBXHM
[1] 2020/12/17 16:03:13.639582 [INF] Server name is NAOYR6QS2GMEQG4TFZF7D3SNFWEL536KSW57ZJUTSPEMZ5UGFF6UBXHM
[1] 2020/12/17 16:03:13.639586 [INF] Server is ready
[1] 2020/12/17 16:03:13.931292 [DBG] 172.17.0.1:45276 - wid:2 - Client connection created
[1] 2020/12/17 16:03:13.948180 [DBG] 172.17.0.1:45280 - wid:3 - Client connection created
[1] 2020/12/17 16:03:13.960071 [DBG] 172.17.0.1:45284 - wid:4 - Client connection created
[1] 2020/12/17 16:03:13.988728 [DBG] 172.17.0.1:45288 - wid:5 - Client connection created
[1] 2020/12/17 16:03:13.993530 [TRC] 172.17.0.1:45288 - wid:5 - <<- [CONNECT {"protocol":1,"version":"1.0.0-114","lang":"nats.ws","echo":false,"verbose":false,"pedantic":false,"name":"client-","auth_token":"3secret"}]
[1] 2020/12/17 16:03:13.993665 [TRC] 172.17.0.1:45288 - wid:5 - "v1.0.0-114:nats.ws:client-" - <<- [PING]
[1] 2020/12/17 16:03:13.993701 [TRC] 172.17.0.1:45288 - wid:5 - "v1.0.0-114:nats.ws:client-" - ->> [PONG]
[1] 2020/12/17 16:03:15.932328 [TRC] 172.17.0.1:45276 - wid:2 - ->> [-ERR Authentication Timeout]
[1] 2020/12/17 16:03:15.932381 [DBG] 172.17.0.1:45276 - wid:2 - Authentication Timeout
[1] 2020/12/17 16:03:15.932411 [DBG] 172.17.0.1:45276 - wid:2 - Client connection closed: Authentication Timeout
[1] 2020/12/17 16:03:15.948879 [TRC] 172.17.0.1:45280 - wid:3 - ->> [-ERR Authentication Timeout]
[1] 2020/12/17 16:03:15.948917 [DBG] 172.17.0.1:45280 - wid:3 - Authentication Timeout
[1] 2020/12/17 16:03:15.948946 [DBG] 172.17.0.1:45280 - wid:3 - Client connection closed: Authentication Timeout
[1] 2020/12/17 16:03:15.960466 [TRC] 172.17.0.1:45284 - wid:4 - ->> [-ERR Authentication Timeout]
[1] 2020/12/17 16:03:15.960566 [DBG] 172.17.0.1:45284 - wid:4 - Authentication Timeout
[1] 2020/12/17 16:03:15.960575 [DBG] 172.17.0.1:45284 - wid:4 - Client connection closed: Authentication Timeout
[1] 2020/12/17 16:03:15.971841 [DBG] 172.17.0.1:45294 - wid:6 - Client connection created
[1] 2020/12/17 16:03:15.976952 [TRC] 172.17.0.1:45294 - wid:6 - <<- [CONNECT {"protocol":1,"version":"1.0.0-114","lang":"nats.ws","echo":false,"verbose":false,"pedantic":false,"name":"client-","auth_token":"3secret"}]
[1] 2020/12/17 16:03:15.995103 [DBG] 172.17.0.1:45288 - wid:5 - "v1.0.0-114:nats.ws:client-" - Client Ping Timer
[1] 2020/12/17 16:03:15.995162 [TRC] 172.17.0.1:45288 - wid:5 - "v1.0.0-114:nats.ws:client-" - ->> [PING]
[1] 2020/12/17 16:03:15.998132 [TRC] 172.17.0.1:45288 - wid:5 - "v1.0.0-114:nats.ws:client-" - <<- [PONG]
[1] 2020/12/17 16:03:16.021763 [TRC] 172.17.0.1:45294 - wid:6 - "v1.0.0-114:nats.ws:client-" - <<- [PING]
[1] 2020/12/17 16:03:16.021813 [TRC] 172.17.0.1:45294 - wid:6 - "v1.0.0-114:nats.ws:client-" - ->> [PONG]
[1] 2020/12/17 16:03:17.017397 [TRC] 172.17.0.1:45288 - wid:5 - "v1.0.0-114:nats.ws:client-" - <<- [PING]
[1] 2020/12/17 16:03:17.017435 [TRC] 172.17.0.1:45288 - wid:5 - "v1.0.0-114:nats.ws:client-" - ->> [PONG]
[1] 2020/12/17 16:03:18.234340 [DBG] 172.17.0.1:45294 - wid:6 - "v1.0.0-114:nats.ws:client-" - Client Ping Timer
[1] 2020/12/17 16:03:18.234407 [TRC] 172.17.0.1:45294 - wid:6 - "v1.0.0-114:nats.ws:client-" - ->> [PING]
[1] 2020/12/17 16:03:18.236898 [TRC] 172.17.0.1:45294 - wid:6 - "v1.0.0-114:nats.ws:client-" - <<- [PONG]
```

If the problem doesn't occur the first time, you can just go on with step 5-7. I usually have the problem after 2-3 tries. It may be related to the timing.

### PR DESCRIPTION
**Pull request by aricart**
- [fix] added peek on connect before resolving the connection
- [fix] added check to options specified options that require matching with the server capabilities before resolving the connection
- [feat] added check that `tls` options are not set on the ws client as they cannot be honored (the connection is wss or ws).

### CODE REVIEW

File: src/ws_transport.ts [hunk 1]
```diff
@@ -52,29 +58,61 @@ export class WsTransport implements Transport {
...
+        this.signal.resolve();
+        return;
+      }
+      const t = DataBuffer.concat(...this.yields);
+      const pm = extractProtocolMessage(t);
+      if (pm) {
+        const m = INFO.exec(pm);
+        if (!m) {
+          if (options.debug) {
+            console.error("!!!", render(t));
```
Comment (kozlovic) [inline src/ws_transport.ts:99]: Was it when you were debugging or planing to leave this here? If so, would use a better text

File: src/ws_transport.ts [hunk 2]
```diff
@@ -52,29 +58,61 @@ export class WsTransport implements Transport {
...
-  async connect(
+  connect(
     server: Server,
     options: ConnectionOptions,
   ): Promise<void> {
     const connected = false;
     const connLock = deferred<void>();
 
+    // ws client doesn't support TLS setting
+    if (options.tls) {
```
Comment (kozlovic) [inline src/ws_transport.ts:72]: So this library must be used in context of web browsers (that are responsible to do the TLS handshake)? In other words, you have no plan to have users be able to connect directly to NATS server with WS and TLS?

**Review by kozlovic — COMMENTED** [review]
Question about one debug statement?

File: src/ws_transport.ts (hunk 1 above)
Comment (aricart) [reply src/ws_transport.ts:99]: this is only shown if you specify the debug flag which renders the protocol - normally the protocol handler prints all this stuff, but here we do. I think it is OK as this is going to be followed by an error.

File: src/ws_transport.ts (hunk 2 above)
Comment (aricart) [reply src/ws_transport.ts:72]: the ws_transport is only used in the context of a browser - so that option is rejected - I have to do a similar thing for some of the options in deno which only takes the ca certificate.

Now - with that said, if they specify an empty tls option `{}` - we could reject the connection if it is not encrypted - this would, ie - they didn't connect to a `wss` URL - We only know this if the URL itself says `wss` - which in the browser world is a 'safe' bet.

**Review by kozlovic — APPROVED** [review]
LGTM
